eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://discovery:8761/eureka/

server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: usersApi
            uri: http://localhost:8090
            predicates:
              - Path=/api/users/**
          - id: sallesApi
            uri: http://localhost:8091
            predicates:
              - Path=/api/salles/**
          - id: equipmentApi
            uri: http://localhost:8092
            predicates:
              - Path=/api/equipments/**
