x-common-environment: &common-env
  SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888

x-common-db-env: &db-env
  SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mygym
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_DATASOURCE_PASSWORD: admin

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: mygym
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mygym-net

  config-server:
    build: ./config-server
    ports:
      - "8888:8888"
    networks:
      - mygym-net
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8888/actuator/health" ]
      interval: 5s
      timeout: 3s
      retries: 5

  discovery-service:
    build: ./discovery-service
    ports:
      - "8761:8761"
    depends_on:
      - config-server
    environment:
      <<: *common-env
    restart: on-failure
    networks:
      - mygym-net

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - config-server
      - discovery-service
    environment:
      <<: *common-env
    networks:
      - mygym-net

  user-service:
    build: ./user-service
    ports:
      - "8090:8090"
    depends_on:
      - config-server
      - discovery-service
      - db
    environment:
      <<: [*common-env, *db-env]
    command: [ "java", "-jar", "app.jar" ]
    restart: on-failure
    networks:
      - mygym-net

  salle-service:
    build: ./salle-service
    ports:
      - "8091:8091"
    depends_on:
      - config-server
      - discovery-service
      - db
    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mygym
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
    command: [ "java", "-jar", "app.jar" ]
    restart: on-failure
    networks:
      - mygym-net

  equipment-service:
    build: ./equipment-service
    ports:
      - "8092:8092"
    depends_on:
      - config-server
      - discovery-service
      - db
    environment:
      <<: *db-env
    command: [ "java", "-jar", "app.jar" ]
    restart: on-failure
    networks:
      - mygym-net

  booking-service:
    build: ./booking-service
    ports:
      - "8093:8093"
    depends_on:
      - config-server
      - discovery-service
      - db
    environment:
      <<: [ *common-env, *db-env ]
    command: [ "java", "-jar", "app.jar" ]
    restart: on-failure
    networks:
      - mygym-net

networks:
  mygym-net:
    driver: bridge
volumes:
  pgdata: